intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{xsimd}: hxx{**} $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_base" "-I$src_base"

# Export options.
#
lib{xsimd}:
{
  cxx.export.poptions = "-I$out_base" "-I$src_base"
  cxx.export.libs = $intf_libs
}

# Install into the libxsimd/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/
  install.subdirs = true
}
